FROM maven:3.9.3-eclipse-temurin-17 
EXPOSE 8081
ADD target/Api_Gateway_Server-0.0.1-SNAPSHOT.jar Api_Gateway_Server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "Api_Gateway_Server-0.0.1-SNAPSHOT.jar"]
